parameters:
  content_security_policy:
    report_uri:
      # Either match (data must contain route name, use that if your logger is included in the app)
      # or plain (data must contain URL)
      method: plain
      data: http://127.0.0.1:8001/csp-violation-logger/new

    # OPTIONAL
    # Routes where directives.strict will be applied instead of directives.lax
    strict_routes:
      - login
      - password_reset
      - password_reset_request
      - registration

    # Either lax or strict
    # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Directives
    # Settings below are a good base setup.
    directives:

      lax:
        base-uri:
          - "'self'"
        default-src:
          - "'self'"
        connect-src:
          - "'self'"
          - https://api.pwnedpasswords.com
        form-action:
          - "'self'"
        frame-ancestors:
          - "'none'"

      # OPTIONAL
      # MANDATORY if strict_routes is defined and not empty
      strict:
        base-uri:
          - "'self'"
        default-src:
          - "'self'"
        connect-src:
          - "'self'"
          - https://api.pwnedpasswords.com
        form-action:
          - "'self'"
        frame-ancestors:
          - "'none'"
