# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt
      cost: '%bcrypt_cost%'

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    in_memory:
      memory: ~
    appbundle:
      id: AppBundle\Service\UserProvider

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~
      guard:
        authenticators:
          - app.security.login_form_authenticator
      logout:
        path: /logout
        target: /
        invalidate_session: false
        handlers:
          - security.logout.handler.account_deletion
      remember_me:
        secret: '%secret%'

  # Note : Access control stops at the FIRST match found so it is best practice to order by criticality and start the
  # list with the most critical path
  #
  # Warning : If in the future the website supports locale prefixes (e.g. "en" or "pt", ALL paths MUST be updated
  # (e.g. with [a-z]{2} pattern, like so: ^/[a-z]{2}/account) or if it supports locales with country specified
  # (e.g. "pt_BR" or "en_US", then [a-z]{2} pattern won't match)
  #
  # If access control is also controller side via @Security annotation, the strictest control will prevail, like so:
  # IS_AUTHENTICATED_ANONYMOUSLY < IS_AUTHENTICATED_FULLY < ROLE_SOMETHING < ROLE_SOMETHING_2 inheriting of ROLE_SOMETHING
  access_control:
    - { path: ^/account, role: ROLE_USER }
    - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
